fincalc/__init__.py
import os
from flask import Flask

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY = 'dev',
    )

    if test_config is None:
        app.config.from_pyfile('config.py', silent=True)
    else: 
        app.config.from_mapping(test_config)
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import views
    app.register_blueprint(views.bp)

    return app 

fincalc/views.py
import base64
from io import BytesIO
from matplotlib.figure import Figure
import seaborn as sns
from pdb import post_mortem
from flask import Blueprint, g, flash, redirect, render_template, request, url_for

bp = Blueprint('views', __name__)

@bp.route('/', methods=('GET','POST'))
def index():
    return render_template('index.html')

@bp.route('/loan', methods=('GET', 'POST'))
def loan():
    if request.method == 'POST':
        if 'reset' in request.form:
                return redirect(url_for('views.loan'))
        error = None
        if not request.form['loanAmount']:
            error = "Paskolos suma neįvesta"
        elif (not request.form['years'] and not request.form['months']):
            error = "Turite pasirinkti bent vieną mėnesį ar vienus metus"

        elif not request.form['interestRate'] or float(request.form['interestRate']) <= 0:
            error = "Įveskite palūkanas didesnes už 0"
        elif not request.form['payFrequency']:
            error = "Pasirinkite mokėjimo dažnį"
        if error is not None:
            flash('Error: ' + error)
            return redirect(url_for('views.loan'))
        else:
            loan_amount = float(request.form['loanAmount'])
            interest_rate = float(request.form['interestRate'])
            if len(request.form['years']) == 0:
                years = 0
            else:
                years = int(request.form['years'])
            if len(request.form['months']) == 0:
                months = 0
            else:
                months = int(request.form['months'])
            if years == 0 and months == 0:
                error = "Turite pasirinkti bent vieną mėnesį ar vienus metus"
                flash("Error: " + error)
                return redirect(url_for('views.loan'))
            pay_frequency = request.form['payFrequency']

            total_months = (years * 12) + months
            loan_details = loan_calculator(loan_amount, interest_rate, pay_frequency, total_months)
            loan_chart = pie_chart(loan_amount, float(loan_details["interest_paid"]))

            return render_template('loan.html', LOAN_DETAILS = loan_details, SUBMIT = True, LOAN_CHART = loan_chart)
    return render_template('loan.html', SUBMIT = False)

@bp.route('/invest', methods=('POST','GET'))
def invest():
    if request.method == 'POST':

        if 'reset' in request.form:
                return redirect(url_for('views.invest'))
        error = None
        if not request.form['initialDeposit'] and not request.form['monthlyDeposit']:
            error = 'Turite pasirinkti pradinį įnašą ar mėnesinį įnešimą'
        elif not request.form['interestRate']:
            error = 'Įveskite palūkanas didesnes už 0.'
        elif not request.form['years']:
            error = 'Nepasirinktote trukmės metais.'
        if error is not None:
            flash('Error: ' + error)
            return redirect(url_for('views.invest'))
        else:

            if len(request.form['initialDeposit']) == 0:
                initial_deposit = 0
            else:
                initial_deposit = float(request.form['initialDeposit'])
            if len(request.form['monthlyDeposit']) == 0:
                monthly_deposit = 0
            else:
                monthly_deposit = float(request.form['monthlyDeposit'])
            if initial_deposit == 0 and monthly_deposit == 0:
                error = 'Turite pasirinkti pradinį įnašą ar mėnesinį įnešimą'
                flash('Error: ' + error)
                return redirect(url_for('views.invest'))




            interest_rate = float(request.form['interestRate'])
            years = int(request.form['years'])
            invest_details = invest_calculator(initial_deposit, monthly_deposit, interest_rate, years)
            yearly_returns = invest_details["returns_each_year"]
            invest_graph = line_graph(yearly_returns, years)
            return render_template('invest.html', INVEST_DETAILS = invest_details, SUBMIT = True, INVEST_GRAPH = invest_graph)

    return render_template('invest.html', SUBMIT = False)

def loan_calculator(loan_amount: float, interest_rate: float, pay_frequency: str, total_months: int) -> dict:
    if pay_frequency == 'monthly':
        period_interest = interest_rate / 1000
        total_periods = total_months
    elif pay_frequency == 'bi-weekly':
        period_interest = interest_rate /2600
        total_periods = (total_months / 12) * 26
    else:
        period_interest = interest_rate / 5200
        total_periods = (total_months / 12) * 52
    total_loan_cost = (
        (loan_amount * period_interest * total_periods)
        /(1-(pow(1+ period_interest, -total_periods)))
    )
    period_payment = round(total_loan_cost / total_periods, 2)
    interest_paid = round(total_loan_cost - loan_amount,2)
    total_loan_cost = round(total_loan_cost, 2)
    loan_details = {"total_loan_cost": total_loan_cost, "period_payment": period_payment, "interest_paid": interest_paid, "period_type": pay_frequency}
    return loan_details

def pie_chart(total_loan : float, interest_paid: float) -> base64:
    pie_list = [total_loan, interest_paid] #list of values for pie chart
    pie_labels = ["Principal", "Interest"]
    colors = sns.dark_palette("#198754", reverse=True)
    fig = Figure()
    ax = fig.subplots()
    fig.set_facecolor("#FFF")
    ax.pie(pie_list, labels=pie_labels,colors = colors, autopct='%.1f%%', explode = [0, .025], )
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches='tight', pad_inches=0.25)
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return data

def invest_calculator(initial_deposit: float, monthly_deposit: float, avg_annual_rate: float, years: int) -> dict:
    #calculation will be done with monthly compounding so years need to be converted
    initial_deposit_return = initial_deposit * pow((1 + avg_annual_rate / 100), years)
    '''
    for the monthly deposits, we are assuming annual compounding to keep things simple, so _monthly_deposit will be multiplied by 12. Credit to https://www.wallstreetiswaiting.com/running-the-numbers-1/calculating-interest-recurring-payments/ for the math regarding monthly contributions.
    '''
    monthly_deposits_return = (
        monthly_deposit * ((pow((1 +avg_annual_rate / 100), years)-1)/(avg_annual_rate / 100)) * 12

    )

    returns_each_year = []

    for i in range(1, years + 1):
        initial_deposit_yearly = initial_deposit * pow((1 + avg_annual_rate / 100), i)
        monthly_deposits_yearly = (
        monthly_deposit * ((pow((1 +avg_annual_rate / 100), i)-1)/(avg_annual_rate / 100)) * 12
    )
        returns_each_year.append(initial_deposit_yearly + monthly_deposits_yearly)

    total = initial_deposit_return + monthly_deposits_return
    total_deposits = initial_deposit + (monthly_deposit * years * 12)
    # A list of yearly values can also be used to create an informative graph
    total = round(total, 2)
    profit = round(total - total_deposits,2)
    total_str = "{:,.2f}".format(total)
    profit_str = "{:,.2f}".format(profit)
    total_deposits_str = "{:,.2f}".format(round(total_deposits, 2))
    invest_details = {"total": total_str, "years": years, "total_deposits":total_deposits_str, "profit":profit_str, "returns_each_year": returns_each_year}
    return invest_details

def line_graph(running_returns :list, years :int) -> base64:

    years_list = list(range(1, years + 1))
    
    fig = Figure()
    ax = fig.subplots()
    
    fig.set_facecolor("#FFF")
    ax.plot(years_list, running_returns, color="#198754")
    ax.set(title=f"Returns over {years} years", xlabel="Years", ylabel="Returns")
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches='tight', pad_inches=0.25)
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return data

fincalc/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Home{% endblock%} -Paskolinis</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />

    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>

    <link rel="icon" href="static\icons8-calculator-16.png" />
  </head>
  <body >
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <div class="container-fluid">
        <a class="navbar-brand link-light" href="{{url_for('views.index')}}">Paskolinis</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link link-light" href="{{url_for('views.index')}}"
                >Pagrindinis</a
              >
              <a class="nav-link link-light" href="{{url_for('views.loan')}}"
                >Paskolos skaiciuokle</a
              >
              <a class="nav-link link-light" href="{{url_for('views.invest')}}"
                >Investavimo skaiciuokle</a
              >
            </div>
          </div>
        </div>
      </div>
    </nav>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
      {{message}}
      <br />
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"/>
        
    </div>
    {% endfor %} {% block content %} {% endblock %}
    <footer class="container-fluid fixed-bottom text-center bg-dark text-white p-2">
      <p>&copy; 2023 Bankrotinis</p>
    </footer>
    <script>
      const flash = document.getElementById("flash");
      const alert = document.getElementById("alert");

      alert.addEventListener("click", function closeAlert(event) {
        flash.remove();
      });
    </script>
  </body>
</html>

fincalc/templates/index.html
{% extends 'base.html' %} {% block content%}

<header class="container text-center mt-5 mb-5">
  <div class="d-flex flex-column flex-lg-row">
    <div class="p-2">
      <img
        class="img-fluid shadow-md rounded"
        src="/static/436.png"
        alt="Illustration of woman standing over houses, reaching for the stars"
      />
    </div>
    <div class="p-2 d-flex flex-column ">
      
      <div class="mb-4">
        <h1 class="display-2">Valdyk savo pinigus</h1>
      
      
        <p class="fs-5 mt-4 text-muted
        ">
        Nezinai ka daryti su pinigais????
        Pasiskolink ar investuok!!!
        </p>
      
      
      </div>
       <div class="d-flex justify-content-center gap-4 mt-4">
        <form  action="{{url_for('views.loan')}}">
          <button class="btn btn-success p-2"typ="submit">Paskolos skaiciuokle</button>
        </form>
        <form  action="{{url_for('views.invest')}}">
          <button  class="btn btn-success p-2">Investavimo skaiciuokle</button>
          </form>
       </div>
        
      </div>
    </div>
  </div>
</header>
<br/>

<section class="text-center p-5 bg-success text-white" >
  <h2 class="display-5"> Pasiek savo finansine laisve investuodamas</h2>
</section>



  

  <section class=" d-flex flex-column flex-lg-row p-5 align-items-center text-muted ">

    <div>
      <img class="img-fluid" src="/static/62.png" alt="Person sitting at desk on computer"/>
    </div>

    <div>
      <h3 class=" mx-auto px-5">Pirmas zingsis - Susimokek skolas</h3>
      <p class="mx-auto px-5 mt-4 text-start" style="max-width: 1200px;">
        Daugeliui iš mūsų skolos yra neišvengiama šiuolaikinio gyvenimo dalis. Būstas,
        sveikatos priežiūra, mokėjimai už automobilį. Sąrašas tęsiasi, bet ne visos skolos
        neišvengiamas. Tokie dalykai kaip kredito kortelių išlaidų sumažinimas arba daugiau
        įperkamas automobilis gali sutaupyti tūkstančius palūkanų. Štai kodėl
        daugelis finansų ekspertų pataria grąžinti visas dideles palūkanas (pvz., kreditą
        kortelės) skolos prieš investuojant. Svarstote imti paskolą, kad pirktumete vertingą pirkinį? Mūsų
        <a class="link-info text-decoration-none" href="{{url_for('views.loan')}}">Paskolos skaiciuokle</a> gali padėti pamatyti mokėtiną sumą.
      </p>
    </div>
   
  </section>

  <section class="d-flex flex-column flex-lg-row  align-items-center p-5 mb-5 bg-success text-white">
    
    <div class="order-2 order-lg-1">
      <h3 class="mx-auto px-5" >Antras žingsnis - investuok į ateitį</h3>
      <p class="mx-auto px-5  mt-4 text-start" style="max-width: 1200px;">
        Investuodami galite priversti palūkanų normas dirbti jums. Kai buvai pasiskolinęs,
        palūkanos tik tuštino tavo piniginę.
        Kai investuoji, viskas atvirkščiai. Netgi investuojant palyginti mažas
        sumos šiandien gali turėti įtakos jūsų ateičiai. Išbandykite mūsų
        <a class="link-info text-decoration-none" href="{{url_for('views.invest')}}">Investavimo skaiciuokle </a>sužinoti ateities gražą.
        </p>
      
    </div>
    <div class="order-1 order-lg-2"><img class="img-fluid" src="/static/72.png" alt="Person standing beside charts and graphs"/></div>
  </section>


{% endblock %}

fincalc/templates/invest.html
{% extends 'base.html'%} {% block title %}Invest{% endblock %} {%block content%}
<header class="container mt-5 mb-5 p-5">
  <div class="d-flex flex-column flex-lg-row align-items-center">
    <div>
      <img src="static/114.png" alt="Woman working on computer with coffee" />
    </div>
    <div>
      <h1 class="text-center display-6">Investavimo skaiciuokle</h1>
      <p class="text-center text-muted">
        Regulerus investavimas, gali pakeistį jūsų ateitį ir sukurti nemažas santaupas.
      </p>

      <form method="POST" id="investForm" class="form text-start">
        <div class="mb-2">
          <label class="form-label" for="initialDeposit"
            >Pradinis įnašas: </label
          ><input
            class="form-control"
            type="number"
            id="initialDeposit"
            name="initialDeposit"
            step="0.01"
            min="0"
            value="{{request.form['initialDeposit']}}"
          />
        </div>
        <div class="mb-2">
          <label class="form-label" for="monthlyDeposit"
            >Mėnesinis įnešimas:</label
          ><input
            class="form-control"
            type="number"
            id="monthlyDeposit"
            name="monthlyDeposit"
            step="0.01"
            min="0"
            value="{{request.form['monthlyDeposit']}}"
          />
        </div>
        <div class="mb-2">
          <label class="form-label" for="interestRate">Palūkanų norma(%): </label
          ><input
            class="form-control"
            type="number"
            id="interestRate"
            name="interestRate"
            step="0.01"
            min="0.1"
            {%
            if
            SUBMIT
            %}
            value="{{request.form['interestRate']}}"
            {%
            else
            %}
            value="10.00"
            {%
            endif
            %}
          />
        </div>
        <div class="mb-2">
          <label class="form-label" for="years">Kiek metų investuosite: </label
          ><input
            class="form-control"
            type="number"
            id="years"
            name="years"
            step="1"
            min="1"
            value="{{request.form['years']}}"
          />
        </div>
        <div class="d-flex flex-row gap-4 justify-content-center mt-4">
          <button
            class="btn btn-success"
            type="submit"
            name="submit"
            value="submit"
          >
            Paskaičiuoti
          </button>
          <button
            class="btn btn-success"
            type="submit"
            name="reset"
            value="reset"
          >
            Nuo pradžių
          </button>
        </div>
      </form>
    </div>
  </div>
</header>

{% if SUBMIT %}

<main class="my-5 p-5 bg-light w-100 h-100">
  <div
    class="d-flex flex-column flex-lg-row justify-content-center align-items-center gap-2"
  >
    <div class="flex-fill py-5 w-100 text-center">
      <h2 class="mb-2">Results:</h2>
      <br />
      <ul class="list-unstyled">
        <li class="mb-1">
          Value After {{INVEST_DETAILS.years}} Years : ${{INVEST_DETAILS.total}}
        </li>
        <li class="mb-1">
          Your Total Deposits: ${{INVEST_DETAILS.total_deposits}}
        </li>
        <li class="mb-1">Total Profits: ${{INVEST_DETAILS.profit}}</li>
      </ul>
    </div>
    <div class="flex-fill w-100">
      <img
        src="data:image/png;base64 ,{{INVEST_GRAPH}}"
        alt="A graph showing investment returns by year"
        class="img-fluid shadow-md rounded"
      />
    </div>
  </div>
  <div id="investResult" class="p-5 mb-5"></div>
</main>

<script defer>
  const element = document.getElementById("investResult");
  element.scrollIntoView();
</script>
{% endif %} {% endblock%}

fincalc/templates/loan.html
{% extends 'base.html' %} {% block title %}Loans{% endblock %} {% block content
%}

<header class="container mt-5 mb-5 p-5">
  <div class="d-flex flex-column flex-lg-row align-items-center">
    <div>
      <img
        class="img-fluid shadow-md rounded"
        src="static/331.png"
        alt="Women having a discussion on couches"
      />
    </div>
    <div>
      <h1 class="text-center display-6">Paskolos skaiciuokle</h1>
      <p class="text-center text-muted">
        Pasiskaiciuokite savo imoka
      </p>

      <form method="POST" id="loanForm" class="form text-start">
        <div class="mb-2">
          <label for="loanAmount" class="form-label">Paskolso suma(€):</label>
          <input
            class="form-control"
            type="number"
            id="loanAmount"
            name="loanAmount"
            value="{{request.form['loanAmount']}}"
            min="0"
            step="0.01"
          />
        </div>
        <div class="mb-2">
          <label for="loanTermYears" class="form-label"
            >Paskolos trukme metais:
          </label>
          <input
            class="form-control"
            id="loanTerm"
            name="years"
            type="number"
            step="1"
            min="0"
            value="{{request.form['years']}}"
          />
        </div>
        <div class="mb-2">
          <label for="loanTermMonths" class="form-label"
            >Paskolos trukme menesiais:
          </label>
          <input
            class="form-control"
            id="loanTerm"
            name="months"
            type="number"
            step="1"
            min="0"
            value="{{request.form['months']}}"
          />
        </div>
        <div class="mb-2">
          <label for="interestRate" class="form-label">Metinės palukanos(%):</label>
          <input
            class="form-control"
            type="number"
            id="interestRate"
            name="interestRate"
            step=".01"
            min="0.1"
            value="{{request.form['interestRate']}}"
          />
        </div>
        <div class="mb-2">
          <label for="payFrequency text-start" class="form-label"
            >Mokėjimo dažnumas:
          </label>
          <select
            class="form-select"
            id="payFrequency"
            name="payFrequency"
            value="{{request.form['payFrequency']}}"
          >
            <option value="monthly" selected>Mėnesinis</option>
            <!-- <option value="bi-weekly">Bi-weekly</option> -->
            <!-- <option value="weekly">Weekly</option> -->
          </select>
        </div>
        <div class="d-flex flex-row gap-4 justify-content-center mt-4">
          <button
            class="btn btn-success"
            type="submit"
            name="submit"
            value="submit"
          >
            Patvirtinti
          </button>
          <button
            class="btn btn-success"
            type="submit"
            name="reset"
            value="reset"
          >
            Perskaičiuoti
          </button>
        </div>
      </form>
    </div>
  </div>
</header>

{% if LOAN_DETAILS and SUBMIT %}

<main class="my-5 p-5 bg-light w-100 h-100">
  <div
    class="d-flex flex-column flex-lg-row justify-content-center align-items-center gap-2"
  >
    <div class="flex-fill py-5 w-100 text-center">
      <h2 class="mb-2">Paskola:</h2>

      <ul class="list-unstyled">
        <li class="mb-1">
          Bendra mokėtina suma: ${{"{:,.2f}".format(LOAN_DETAILS.total_loan_cost)}}
        </li>
        <li class="mb-1">
          Mėnesinis mokėjimas: ({{LOAN_DETAILS.period_type}}):
          ${{"{:,.2f}".format(LOAN_DETAILS.period_payment)}}
        </li>
        <li class="mb-1">
          Išviso mokamos palūkanos: ${{"{:,.2f}".format(LOAN_DETAILS.interest_paid)}}
        </li>
      </ul>
    </div>
    <div class="flex-fill w-100">
      <img
        class="img-fluid shadow-md rounded"
        src="data:image/png;base64 ,{{LOAN_CHART}}"
        alt="A pie chart comparing interest to principal"
      />
    </div>
  </div>
  <div id="loanResult" class="p-5 mb-5"></div>
</main>

<script defer>
  const element = document.getElementById("loanResult");
  element.scrollIntoView();
</script>
{% endif %} {% endblock %}